apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexclipper-api
  labels:
    app: nexclipper-api
    version: v1
  namespace: nexclipper
spec:
  selector:
    matchLabels:
      app: nexclipper-api
  template:
    metadata:
      name: nexclipper-api
      labels:
        app: nexclipper-api
    spec:
      containers:
        - name: nexserivce
          image: p8s.me/nexclipper/monitorapi:0.3.5
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 512Mi
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
              name: nexclipper-api
          env:
            - name: PROMETHEUS_ENDPOINT
              value: "http://nc-promscale-connector.nexclipper:9201"
            - name: REDIS_ENDPOINT
              value: "192.168.3.21"
            - name: REDIS_PORT
              value: '32507'
            - name: OPENSTACK_ENDPOINT
              value: "http://192.168.1.14"
            - name: OPENSTACK_USERNAME
              value: "admin"
            - name: OPENSTACK_PASSWORD
              value: "0000"
            - name: OPENSTACK_SENLINPORT
              value: "8778"
            - name: OPENSTACK_NEUTRONPORT
              value: "9696"
            - name: OPENSTACK_USERDOMAIN
              value: "default"